version: '3.8'

services:
  web:
    build: ./frontend
    ports:
      -3000:3000
  api:
    build: ./backend
    ports:
      -5000:5000
  db:
    image: postgres:alpine3.18
    ports:
      -5432:5432
    volumes:
      -trivia: /var/lib/postgresql/data
volumes:
  -trivia:

